@startuml AudioServer

Package "AudioServer" {
    [AudioFlinger] <<service>>
    [AudioPolicyService] <<service>>
    [AAudioService] <<service>>
    [SoundTriggerHwService] <<service>>
}

skinparam component {
    backgroundColor<<service>> #F7D18C
}

skinparam Package {
    backgroundColor #98C482
    BoxPadding 10px
}
@endumll