@startuml AudioServer

Package "AudioServer" {
    [AudioFlinger] <<service>>
    [AudioPolicyService] <<service>>
    [AAudioiService] <<service>>
    [SoundTriggerHwService] <<service>>
}

!include ../template.iuml
@endumll