@startuml Android Audio Stack
    allow_mixing
    hide stereotype

    package "User space" <<userspace>> {

        package Application <<userspace_package>> {
            component JNI
        }
        
        package AudioClient <<userspace_package>> {
            component AAudioClient
            component libaudioclient
        }

        package AudioServer <<userspace_package>> {
            component AAudioService
            component AudioFlinger
            component AudioPolicyManager
            component SoundTriggerHwService
        }

        package HAL <<userspace_package>> {
            component AudioHAL
            component TinyALSA

            AudioHAL -> TinyALSA
        }

        JNI ---> libaudioclient

        libaudioclient  --->AudioFlinger
        AAudioClient    --->AAudioService


        AudioFlinger  ---> AudioHAL
        AAudioService ---> AudioHAL
    }

    package "Kernel Space" <<kernelspace>> {
        component "ALSA Driver"
    }

TinyALSA ---> "ALSA Driver"

!include template.iuml



@enduml